theme: jekyll-theme-minimal
title: Awesome Academic Writing
description: A curated list of awesome things related to academic writing.
# logo: "/assets/images/just-the-docs.png"
show_downloads: false
# google_analytics: [Your Google Analytics tracking ID]
